import { useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Alert, Button, Form, Input, InputNumber, Result } from 'antd'
import { ArrowUpFromLine } from 'lucide-react'
import { api } from '../api'
import { PageHeader, QueryState, SectionHeader, StatusTag } from '../components/Common'
import type { BitcoinWithdrawal } from '../types'

type FormValue={to_address:string;amount_sats:number}

export default function BitcoinWithdrawPanel({userId}:{userId:number}){const[form]=Form.useForm<FormValue>();const[created,setCreated]=useState<BitcoinWithdrawal>();const detail=useQuery({queryKey:['btc-withdrawal',created?.id],queryFn:()=>api.bitcoinWithdrawal(created!.id),enabled:Boolean(created?.id),refetchInterval:(query)=>['COMPLETED','FAILED'].includes(query.state.data?.status??'')?false:3000});const current=detail.data??created;const mutation=useMutation({mutationFn:(value:FormValue)=>api.createBitcoinWithdrawal(userId,crypto.randomUUID(),value),onSuccess:setCreated});if(current)return <><PageHeader title="BTC 提币进度"/><section className="panel withdrawal-result"><Result status={current.status==='FAILED'?'error':current.status==='COMPLETED'?'success':'info'} title={current.status==='COMPLETED'?'提币已完成':'BTC 提币处理中'} subTitle={`BTC 提币单 #${current.id}`}/><div className="withdrawal-detail-grid"><div><span>状态</span><StatusTag status={current.status}/></div><div><span>金额</span><strong>{current.amount_sats} sat</strong></div><div><span>目标地址</span><strong className="mono break-all">{current.to_address}</strong></div><div><span>费率</span><strong>{current.fee_rate_sat_vb} sat/vB</strong></div></div><Button onClick={()=>{setCreated(undefined);form.resetFields()}}>发起新的提币</Button></section></>;return <><PageHeader title="提币 BTC"/><section className="panel withdraw-form-panel"><SectionHeader title="Bitcoin Signet 提币"/><QueryState loading={false} error={mutation.error}/><Form form={form} layout="vertical" onFinish={(value)=>mutation.mutate(value)}><Form.Item label="Signet 地址" name="to_address" rules={[{required:true},{pattern:/^tb1q[023456789acdefghjklmnpqrstuvwxyz]{38}$/,message:'请输入有效的 Signet P2WPKH 地址'}]}><Input className="mono" placeholder="tb1q..."/></Form.Item><Form.Item label="金额" name="amount_sats" rules={[{required:true}]}><InputNumber min={1} precision={0} addonAfter="sat" style={{width:'100%'}}/></Form.Item>{mutation.isError&&<Alert type="error" showIcon title={mutation.error.message}/>}<Button htmlType="submit" type="primary" danger block loading={mutation.isPending} icon={<ArrowUpFromLine size={17}/>}>提交提币</Button></Form></section></>}
